### ISSUE TITLE
Bump maven-javadoc-plugin from 3.4.1 to 3.5.0

### ISSUE THREAD

**Issue by arolfes** [Taskana/taskana#2175]
After Upgrade `maven-javadoc-plugin` the following error occured during build from `taskana-rest-spring`

```
javadoc: error - In doclet class capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
        at capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet.createObjectMapper(ExtractDocumentationAsJsonDoclet.java:94)
        at capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet.start(ExtractDocumentationAsJsonDoclet.java:44)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at jdk.javadoc/com.sun.tools.javadoc.main.DocletInvoker.invoke(DocletInvoker.java:333)
        at jdk.javadoc/com.sun.tools.javadoc.main.DocletInvoker.start(DocletInvoker.java:212)
        at jdk.javadoc/com.sun.tools.javadoc.main.Start.parseAndExecute(Start.java:446)
        at jdk.javadoc/com.sun.tools.javadoc.main.Start.begin(Start.java:238)
        at jdk.javadoc/com.sun.tools.javadoc.main.Start.begin(Start.java:224)
        at jdk.javadoc/com.sun.tools.javadoc.Main.execute(Main.java:174)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:420)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:345)
        at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
        at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 16 more
Command line was: /opt/graalvm/graalvm-22.3.1-java11/bin/javadoc @options @packages
```

**Comment by arolfes** [comment]
Adding `additionalDependencies` or `bootclasspathArtifacts` doesn’t solve the problem

example:

```xml
<additionalDependencies>
                <additionalDependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-databind</artifactId>
                  <version>2.13.4.2</version>
                </additionalDependency>
              </additionalDependencies>
              <bootclasspathArtifacts>
                <bootclasspathArtifact>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-databind</artifactId>
                  <version>2.13.4.2</version>
                </bootclasspathArtifact>
              </bootclasspathArtifacts>

```
